# FROM ubuntu:latest
FROM osrf/ros:humble-desktop-full
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> ~/.bashrc

LABEL author="Aaron Tran <aarontranpvt@gmail.com>"

RUN rm /bin/sh && ln -s /bin/bash /bin/sh
SHELL ["/bin/bash", "-c"]
RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker
RUN DEBIAN_FRONTEND=noninteractive \
  apt-get update \
  && apt-get install -y python3 \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
      apt-get -y install sudo

RUN apt-get update && apt-get install -y \
    git \
    python3-pip \
    curl \
    zip \
    unzip \
    tar \
    cmake \
    build-essential \
    g++ \
    ninja-build \
    libeigen3-dev

#Convenient packages
RUN apt-get install -y plocate 
RUN apt-get install -y iputils-ping
RUN apt-get update && apt-get install -y gdb
RUN apt-get install -y ffmpeg
RUN pip3 install notebook

#Necessary Libraries
# RUN pip3 install pandas
# RUN pip3 install openpyxl
# RUN pip3 install scikit-learn
# RUN pip3 install pytorch-mppi[tune]
# RUN pip3 install pytorch-icem

#X11 Forwarding
RUN apt install -y xauth

WORKDIR /home

RUN useradd --create-home Aaron
RUN echo "Aaron:1234" | chpasswd && adduser Aaron sudo

WORKDIR "/home/Aaron"

